defaults:
  - mode: train
  - model: msg3d
  - dataset: debug
  - optimizer: sttformer
  - miner: multi_similarity
  - embedder_loss: triplet_margin
  - trainer: debug
  - tester: debug
  - loss: default
  - embedder: default
  - transform: minimal
  - end_of_epoch_hook: sttformer