defaults:
  - model: sttformer
  - dataset: sttformer_joint_test
  - tester: use_amp_false
  - embedder: default
  - mode: test
hydra:
  run:
    dir: ./outputs/test_sttformer_joint
num_train_labels: 90