defaults:
  - mode: final_train
  - model: agcn
  - dataset: ntu_graph
  - optimizer: rmsprop
  - miner: multi_similarity
  - embedder_loss: triplet_margin
  - trainer: test
  - loss: default
  - embedder: default
  - transform: minimal
  - use_amp: amp_false