defaults:
  - model: hd-gcn_bone_com_1
  - dataset: hd-gcn_bone_com_1_with_val_test
  - tester: use_amp_false
  - embedder: default
  - mode: test
hydra:
  run:
    dir: ./outputs/test_hd-gcn_bone_com_1_with_val
num_train_labels: 90