defaults:
  - model: hyperformer
  - dataset: hyperformer_joint_test
  - tester: use_amp_false
  - embedder: default
  - mode: test
hydra:
  run:
    dir: ./outputs/test_hyperformer_joint
num_train_labels: 100