defaults:
  - mode: train
  - model: agcn
  - dataset: val_samples
  - optimizer: rmsprop
  - miner: multi_similarity
  - embedder_loss: triplet_margin
  - trainer: train
  - tester: use_amp_true
  - loss: default
  - embedder: default
  - transform: minimal