model_name: "dgstgcn"
model_args:
  dgstgcn_args:
    gcn_ratio: 0.125
    gcn_ctr: "T"
    gcn_ada: "T"
    tcn_ms_cfg:
      - - 3
        - 1
      - - 3
        - 2
      - - 3
        - 3
      - - 3
        - 4
      - - "max"
        - 3
      - "1x1"
    graph_cfg:
      layout: "nturgb+d"
      mode: "random"
      num_filter: 8
      init_off: 0.04
      init_std: 0.02
  head_args:
    num_classes: 120
    in_channels: 256
