work_dir: ./work_dir/ntu120/xsub_joint
run_mode: train

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: gendata/ntu120/NTU_one_shot_npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: gendata/ntu120/NTU_one_shot_npy
  split: test
  debug: False
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False

# model
model: model.sttformer.Model
model_args:
  # n in paper, the number of frames in a tuple
  len_parts: 6
  # Seems to be T
  num_frames: 120
  num_joints: 25
  # TODO: Gotta change it to 100
  num_classes: 120
  num_heads: 3
  # TODO: Not exactly clear
  kernel_size: [3, 5]
  num_persons: 2
  # for feature mapping layer
  num_channels: 3
  # Whether to use positional encoding or not
  use_pes: True
  # The configs for the layers of STTA and IFFA. Number of configs == L, the number of layers of STTA and IFFA
  config: [[64,  64,  16], [64,  64,  16], 
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64], 
           [256, 256, 64], [256, 256, 64]]

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [60, 80]
warm_up_epoch: 5

# training
device: [0,1]
cuda_visible_device: '2,3'
batch_size: 64
test_batch_size: 64
num_epoch: 90
nesterov: True
