gpu run python3 train.py --config-name train_hd_gcn_joint_com_21_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True +trainer.save_epochs=[]
gpu run python3 train.py --config-name train_hd_gcn_joint_com_2_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True +trainer.save_epochs=[]
gpu run python3 train.py --config-name train_hd_gcn_joint_com_21_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True +trainer.save_epochs=[]
gpu run python3 train.py --config-name train_hd_gcn_bone_com_21_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True +trainer.save_epochs=[]
gpu run python3 train.py --config-name train_hd_gcn_bone_com_2_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True +trainer.save_epochs=[]
gpu run python3 train.py --config-name train_hd_gcn_bone_com_21_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True +trainer.save_epochs=[]

gpu run python3 train.py --config-name train_dgstgcn_joint_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True
gpu run python3 train.py --config-name train_dgstgcn_joint_motion_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True
gpu run python3 train.py --config-name train_dgstgcn_bone_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True
gpu run python3 train.py --config-name train_dgstgcn_bone_motion_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True

gpu run python3 train.py --config-name train_sttformer_joint_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=Tru
gpu run python3 train.py --config-name train_sttformer_bone_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=Tru
gpu run python3 train.py --config-name train_sttformer_joint_vel_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=Tru
gpu run python3 train.py --config-name train_sttformer_bone_vel_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True

#gpu run python3 train.py --config-name train_hyperformer_bone_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True
#gpu run python3 train.py --config-name train_hyperformer_bone_vel_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True
#gpu run python3 train.py --config-name train_hyperformer_joint_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True
#gpu run python3 train.py --config-name train_hyperformer_joint_vel_with_val +mode.type=train_from_scratch +mode.model_folder=example_saved_models +trainer.save_epochs=[] +dataset.data_kwargs.val_samples.use_uniform_sample=True +dataset.data_kwargs.val.use_uniform_sample=True +dataset.data_kwargs.train.use_uniform_sample=True