python3 train.py --config-name train_sttformer_joint_motion_no_val +mode.type=train_from_scratch +trainer.save_epochs=[26]
python3 train.py --config-name train_hd_gcn_bone_com_1_no_val +mode.type=train_from_scratch +trainer.save_epochs=[44]
python3 train.py --config-name train_hd_gcn_bone_com_2_with_val +mode.type=train_from_scratch +trainer.save_epochs=[]
python3 train.py --config-name train_hd_gcn_bone_com_21_with_val +mode.type=train_from_scratch +trainer.save_epochs=[]
python3 train.py --config-name train_hd_gcn_joint_com_1_with_val +mode.type=train_from_scratch +trainer.save_epochs=[]
python3 train.py --config-name train_hd_gcn_joint_com_2_with_val +mode.type=train_from_scratch +trainer.save_epochs=[]
python3 train.py --config-name train_hd_gcn_joint_com_21_with_val +mode.type=train_from_scratch +trainer.save_epochs=[]
