name: "ntu120_oneshot_debug"
data_path: "../../data/ntu/one_shot/train_data_joint.npy"
label_path: "../../data/ntu/one_shot/train_label.pkl"
data_dir: "/ntu/debug/"
dataset_split:
  val_classes:
    - 14
    - 62
    - 110
  mem_limits:
    val_samples:
      100000
    val:
      100000
    train:
      33333
debug:
  true
data_kwargs:
  train:
    train:
      true
  val_samples:
    train:
      false
  val:
    train:
      false