name: "ntu120_oneshot_hd-gcn"
data_path: "../../../STTTFormer/gendata/ntu120/NTU120_one_shot/x_train.npy"
label_path: "../../../STTTFormer/gendata/ntu120/NTU120_one_shot/y_train.npy"
name_path: "../../../STTTFormer/gendata/ntu120/NTU120_one_shot/names_train.npy"
data_dir: "/ntu/sttformer/"
dataset_split:
  val_classes: []
  mem_limits:
    val_samples:
      0
    val:
      0
    train:
      0
debug:
  false
data_kwargs:
  val_samples:
    split: test
    window_size: 64
    p_interval: [0.95]
    bone: False
    debug: False
  val:
    split: test
    window_size: 64
    p_interval: [0.95]
    bone: False
    debug: False
  train:
    split: train
    debug: False
    random_choose: False
    random_shift: False
    random_move: False
    window_size: 64
    normalization: False
    random_rot: True
    p_interval: [0.5, 1]
    bone: False

