name: "ntu120_oneshot_hyperformer"
data_path: "../../../STTTFormer/gendata/ntu120/NTU120_one_shot/x_train.npy"
label_path: "../../../STTTFormer/gendata/ntu120/NTU120_one_shot/y_train.npy"
name_path: "../../../STTTFormer/gendata/ntu120/NTU120_one_shot/names_train.npy"
data_dir: "/ntu/hyperformer/"
dataset_split:
  val_classes:
    - 2
    - 14
    - 26
    - 38
    - 50
    - 62
    - 74
    - 86
    - 98
    - 110
  mem_limits:
    val_samples:
      0
    val:
      0
    train:
      0
debug:
  false
data_kwargs:
  val_samples:
    split: test
    debug: False
    window_size: 64
    p_interval: [0.95]
    vel: True
    bone: False
    hyperformer: True
  val:
    split: test
    debug: False
    window_size: 64
    p_interval: [0.95]
    vel: True
    bone: False
    hyperformer: True
  train:
    random_choose: False
    random_shift: False
    random_move: False
    window_size: 64
    normalization: False
    random_rot: True
    p_interval: [0.5, 1]
    vel: True
    bone: False
    hyperformer: True

