name: "ntu120_oneshot_raphael"
data_path: "/home/work/PycharmProjects/MA/MasterThesis/graph_metric_learning-master/data/ntu/one_shot/train_data_joint.npy"
label_path: "/home/work/PycharmProjects/MA/MasterThesis/graph_metric_learning-master/data/ntu/one_shot/train_label.pkl"
data_dir: "/ntu/raphael/"
dataset_split:
  val_classes:
    - 2
    - 14
    - 26
    - 38
    - 50
    - 62
    - 74
    - 86
    - 98
    - 110
  mem_limits:
    val_samples:
      100000
    val:
      100000
    train:
      33333
debug:
  false
data_kwargs:
  train:
    train:
      false
  val_samples:
    train:
      false
  val:
    train:
      false